// Concentra Challenges catalog data
// Categories with challenges in source-PDF order

window.CATALOG = {
  meta: {
    title: "Program Catalog",
    edition: "VERSION 26 · CHALLENGE LIBRARY",
    year: "2026 EDITION",
    publisher: "CONCENTRA · CHALLENGES PROGRAM",
  },
  categories: [
    {
      id: "fitness",
      name: "Fitness",
      blurb: "Build movement into the workday. From 10,000-step challenges to burpees, planks, and stair climbs — these challenges meet participants wherever they are and gently raise the floor.",
      // Pre-curated stock photos — fitness/movement
      images: [
        "images/fitness/plank-you-very-much.jpg",
        "images/fitness/step-it-up.jpg",
        "images/fitness/lap-in-lap-out.jpg",
        "images/fitness/30-days-of-fitness.jpg",
        "images/fitness/trip-around-the-world.jpg",
        "images/fitness/15-15.jpg",
        "images/fitness/stare-down-the-stairs.jpg",
        "images/fitness/what-benefits-you-benefits-me.jpg",
        "images/fitness/march-to-may.jpg",
        "images/fitness/zombie-challenge.jpg",
        "images/fitness/spring-into-activity.jpg",
        "images/fitness/my-activity-tracker.jpg",
        "images/fitness/couch-to-5k.jpg",
        "images/fitness/stay-fit-at-home.jpg",
        "images/fitness/excuse-me-i-burpeed.jpg",
        "images/fitness/stretch-it-out.jpg",
        "images/fitness/go-for-the-gold.jpg"
      ],
      challenges: [
        { title: "Plank You Very Much", chip: "30 DAYS", desc: "Firm your abs, core, shoulders, arms, and glutes with this simple, effective exercise. Time to crank your core and become a plank ninja.", length: "30 days", tracking: "Plank time" },
        { title: "Step It Up", chip: "6 / 8 / 12 WEEKS", desc: "Taking steps is the first step to stepping up your fitness in the right direction. Log 10,000 steps in a day.", length: "6, 8, or 12 weeks", tracking: "Number of steps" },
        { title: "Lap In — Lap Out", chip: "4 WEEKS", desc: "Before you come in to work in the morning, lap in. Before you leave in the evening, lap out. Get a walking circuit and lap in, lap out, each day.", length: "4 weeks", tracking: "Number of laps each day" },
        { title: "30 Days of Fitness", chip: "30 DAYS", desc: "Writing it down makes it real and easier to follow through. Resolve to do at least one thing every day to improve your fitness.", length: "30 days", tracking: "Length of fitness routine" },
        { title: "Trip Around the World", chip: "5 WEEKS", desc: "Walk the globe and learn about your world as you move through it. As participants progress, we provide health tips and recipes from each region.", length: "5 weeks", tracking: "Steps" },
        { title: "15-15", chip: "30 DAYS", desc: "Fitness is not as hard or as time-consuming as we've been told. Take 15 minutes during your day, and log what you added.", length: "30 days", tracking: "Length of daily activity" },
        { title: "Stare Down the Stairs", chip: "30 DAYS", desc: "A core wellness principle: never stand as long as you're still able to walk. Take a flight of stairs because you can.", length: "30 days", tracking: "Flights of stairs taken" },
        { title: "What Benefits You Benefits Me", chip: "90 DAYS", desc: "Get your friends together and show up for a benefit walk or run. You'll feel better inside and out — and help others in the process.", length: "90 days", tracking: "Running time" },
        { title: "March to May", chip: "12 WEEKS", desc: "Walking is good for weight management, chronic disease risk reduction, and stress control. Let's march to May.", length: "12 weeks", tracking: "Number of steps" },
        { title: "Zombie Challenge", chip: "5 WEEKS", desc: "The zombies are coming. Keep moving and stay ahead of them — they get faster each week. Don't get caught.", length: "5 weeks", tracking: "Steps" },
        { title: "Spring Into Activity", chip: "7 WEEKS", desc: "Walking is good for weight management, chronic disease risk reduction, and stress control.", length: "7 weeks", tracking: "Steps" },
        { title: "My Activity Tracker", chip: "1 YEAR", desc: "Track your monthly steps through a wearable device, pedometer, or by choosing an activity from a list of 200.", length: "1 year", tracking: "Number of steps" },
        { title: "Couch to 5K", chip: "8 WEEKS", desc: "Get off the couch and start moving. By the end of this challenge, participants are ready to complete a 5K.", length: "8 weeks", tracking: "Distance and time" },
        { title: "Stay Fit at Home", chip: "7 WEEKS", desc: "Weekly strategies to make regular short bursts of movement part of the daily routine — at home or in the office.", length: "7 weeks", tracking: "Amount of time" },
        { title: "Excuse Me, I Burpee'd", chip: "3 WEEKS", desc: "The burpee fuses aerobic and strength training into one full-body exercise. No equipment needed — it goes anywhere.", length: "3 weeks", tracking: "Number of burpees" },
        { title: "Stretch It Out", chip: "28 DAYS", desc: "Stretching is like giving yourself an instant massage. Great for injury prevention, and it can be done in many forms, almost anywhere.", length: "28 days", tracking: "Time" },
        { title: "Go for the Gold", chip: "4 WEEKS", desc: "Four fitness challenges in one. Each week brings a new focus: planks, squats, push-ups, and sit-ups. Meet or exceed the weekly goal to win gold.", length: "4 weeks", tracking: "Weekly goal completion" },
      ],
    },
    {
      id: "nutrition",
      name: "Nutrition",
      blurb: "Better food, simpler choices. These challenges build awareness around what we eat — labels, hydration, color, sugar, caffeine — and turn small daily adjustments into lasting habits.",
      images: [
        "images/nutrition/veg-out.jpg",
        "images/nutrition/hydration-challenge.jpg",
        "images/nutrition/fruit-for-dessert.jpg",
        "images/nutrition/get-real.jpg",
        "images/nutrition/make-a-fake-food-at-home.jpg",
        "images/nutrition/cancer-fighting-foods.jpg",
        "images/nutrition/take-your-one-a-day.jpg",
        "images/nutrition/take-out-the-trash.jpg",
        "images/nutrition/color-your-plate.jpg",
        "images/nutrition/kick-the-can.jpg",
        "images/nutrition/brown-bag-lunch.jpg",
        "images/nutrition/caffeine-count.jpg",
        "images/nutrition/healthy-snacks-and-sides.jpg",
        "images/nutrition/lose-the-sugar.jpg",
        "images/nutrition/no-night-time-munchies.jpg",
        "images/nutrition/the-one-veg-boost.jpg",
        "images/nutrition/label-smart.jpg"
      ],
      challenges: [
        { title: "Veg Out", chip: "1 WEEK", desc: "An easy way to better nutrition: practice eating more vegetables. Take one week and eat a vegetarian diet.", length: "1 week", tracking: "Number of vegetables" },
        { title: "Hydration Challenge", chip: "3 WEEKS", desc: "Hydration is critical to so many of the body's functions. After just 3 weeks, participants notice a real difference.", length: "3 weeks", tracking: "Daily intake in ounces of approved drinks" },
        { title: "Fruit for Dessert", chip: "2 WEEKS", desc: "Fruit is more delicious than you realize, especially as dessert. Health up your meal with a piece of fruit at the end.", length: "2 weeks", tracking: "Fruit for dessert (yes/no)" },
        { title: "Get Real", chip: "30 DAYS", desc: "People put things in their mouths that just aren't food. Find the faux-food fakers in your products and get them out.", length: "30 days", tracking: "Faux-free day (yes/no)" },
        { title: "Make a Fake Food at Home", chip: "1 WEEK", desc: "Everyone has a faux food they love. Own up to it — and we'll provide an at-home solution for making it yourself.", length: "1 week", tracking: "Made the recipe (yes/no)" },
        { title: "Cancer-Fighting Foods", chip: "30 DAYS", desc: "The best cancer fighters on earth are also the cheapest. Get the list, make them, and share with others.", length: "30 days", tracking: "Ate a cancer-fighting food (yes/no)" },
        { title: "Take Your One a Day", chip: "30 DAYS", desc: "The best supplement on earth is a piece of fruit. Add a piece of fruit during your day. Just one — start there.", length: "30 days", tracking: "Amount of fruit eaten" },
        { title: "Take Out the Trash", chip: "30 DAYS", desc: "Antioxidants clean your system by removing the waste products of cellular metabolism. Add high-antioxidant foods to your diet.", length: "30 days", tracking: "Drop-down of foods to choose from" },
        { title: "Color Your Plate", chip: "6 WEEKS", desc: "Add the rainbow of colors to your plate every day. The treasure: improved health and lower weight along the way.", length: "6 weeks", tracking: "Number of colorful foods eaten" },
        { title: "Kick the Can", chip: "30 DAYS", desc: "Sodas are not real food. There are no soda bushes. Go one month soda-free.", length: "30 days", tracking: "Number of sodas (goal: decrease)" },
        { title: "Brown Bag Lunch", chip: "30 DAYS", desc: "During this challenge, bring a packed lunch to work each day.", length: "30 days", tracking: "Bring your lunch (yes/no)" },
        { title: "Caffeine Count", chip: "2 WEEKS", desc: "The FDA considers 400 mg of caffeine per day a safe amount for healthy adults. This challenge is about awareness — how much, and from where.", length: "2 weeks", tracking: "Milligrams of caffeine" },
        { title: "Healthy Snacks and Sides", chip: "4 WEEKS", desc: "Choose healthier options for snacks and sides. Learn what ingredients to look for — and what to skip.", length: "4 weeks", tracking: "Number of healthy snacks/sides" },
        { title: "Lose the Sugar", chip: "1 WEEK", desc: "We eat an average of 140 pounds of sugar per person, every year. Reduce consumption and pull your sweet tooth out.", length: "1 week", tracking: "Sweet-tooth rating" },
        { title: "No Night-Time Munchies", chip: "3 WEEKS", desc: "Giving your body a period to rest and digest is a good thing. Fast from evening into morning — and feel the difference.", length: "3 weeks", tracking: "Did you snack" },
        { title: "The One-Veg Boost", chip: "12 WEEKS", desc: "Small changes lead to big results. Add just one vegetable to at least one meal each day. Tiny shifts add up.", length: "12 weeks", tracking: "Yes/no for eating a vegetable that day" },
        { title: "Label Smart", chip: "28 DAYS", desc: "Build confidence in reading ingredient labels so you can make informed, heart-healthy, energy-supporting food choices.", length: "28 days", tracking: "Number of food labels read" },
      ],
    },
    {
      id: "weight-loss",
      name: "Weight Loss",
      blurb: "Sustainable change, not crash diets. Train your appetite, eat at meal times, and focus on portion size and presence — habits that hold long after the challenge ends.",
      images: [
        "images/weight-loss/no-weigh-no-way.jpg",
        "images/weight-loss/stop-overconsumption.jpg",
        "images/weight-loss/sensual-eating-practice.jpg",
        "images/weight-loss/join-the-small-pants-club.jpg",
        "images/weight-loss/eat-at-meal-times.jpg",
        "images/weight-loss/play-survivor.jpg",
        "images/weight-loss/pull-your-sweet-tooth.jpg"
      ],
      challenges: [
        { title: "No Weigh, No Way", chip: "30 DAYS", desc: "If you're an over-analyzer, a great strategy is to let go. Go an entire month without weighing yourself.", length: "30 days", tracking: "How clothes feel (1–3 scale)" },
        { title: "Stop Overconsumption", chip: "30 DAYS", desc: "Eat all you want — just want less. Train your appetite downward to cure overconsumption, calories, and weight in one go.", length: "30 days", tracking: "Number of portions consumed" },
        { title: "Sensual Eating Practice", chip: "1 WEEK", desc: "The more you taste your food, the less you're hungry for it. Focus on flavor at a meal, and judge how it helps control cravings.", length: "1 week", tracking: "Drop-down of food tasting options" },
        { title: "Join the Small Pants Club", chip: "30 DAYS", desc: "Remember those skinny jeans? Drop one size and have to buy smaller pants.", length: "30 days", tracking: "Drop-down of how pants feel" },
        { title: "Eat at Meal Times", chip: "1 WEEK", desc: "Healthy people eat at meal times — not all the time. Train your body to ban mid-meal munchies and return to a 3-meal pattern.", length: "1 week", tracking: "Number of between-meal snacks" },
        { title: "Play Survivor", chip: "30 DAYS", desc: "Don't worry about losing weight — just survive one month without adding pounds. Day 1 to 31 without gaining.", length: "30 days", tracking: "Weight" },
        { title: "Pull Your Sweet Tooth", chip: "30 DAYS", desc: "Average sugar intake: 140 pounds per person, per year. Go sugar-free for one month and pull that sweet tooth out.", length: "30 days", tracking: "Rate your sweet tooth (0–10)" },
      ],
    },
    {
      id: "mindfulness",
      name: "Mindfulness",
      blurb: "Mental wellbeing is part of physical wellbeing. Sleep, gratitude, laughter, breathwork, and digital boundaries — the quiet daily practices that lower stress and lift mood.",
      images: [
        "images/mindfulness/gratitude-inventory.jpg",
        "images/mindfulness/no-complaint-week.jpg",
        "images/mindfulness/laugh-out-loud.jpg",
        "images/mindfulness/meditation-mornings.jpg",
        "images/mindfulness/find-your-fun.jpg",
        "images/mindfulness/better-sleep-challenge.jpg",
        "images/mindfulness/unplug-and-unwind.jpg",
        "images/mindfulness/breathe-in-breathe-out.jpg",
        "images/mindfulness/clean-up-the-clutter.jpg",
        "images/mindfulness/reading-challenge.jpg",
        "images/mindfulness/choose-kindness.jpg",
        "images/mindfulness/breaking-bad-habits.jpg",
        "images/mindfulness/aim-smart-goal-setting.jpg",
        "images/mindfulness/heart-healthy-behaviors.jpg",
        "images/mindfulness/watch-your-wallet.jpg",
        "images/mindfulness/journal-daily-reflection.jpg"
      ],
      challenges: [
        { title: "Gratitude Inventory", chip: "1 WEEK", desc: "Good is out there — be present to it. Take a morning inventory of things you are grateful for. They can be big or small.", length: "1 week", tracking: "Drop-down of things you're grateful for" },
        { title: "No Complaint Week", chip: "3 WEEKS", desc: "Complaint is like emotional smog. Clear the air and you see better, breathe easier, and just feel better.", length: "3 weeks", tracking: "Drop-down on complaining increase/decrease" },
        { title: "Laugh Out Loud", chip: "1 WEEK", desc: "Laughter is an addictive drug with only good side effects. Laugh out loud every day for one week.", length: "1 week", tracking: "Number of times you laughed" },
        { title: "Meditation Mornings", chip: "1 WEEK", desc: "Pre-set your mind for a lower stress response. Set aside 15 minutes in the morning to change your physiology — and your mood.", length: "1 week", tracking: "Time spent meditating" },
        { title: "Find Your Fun", chip: "1 WEEK", desc: "Do at least one thing you find fun every day for a week.", length: "1 week", tracking: "Number of fun things you did" },
        { title: "Better Sleep Challenge", chip: "30 DAYS", desc: "Nearly 30% of adults say they aren't getting enough quality sleep. Learn practical tips to improve your sleep — for good.", length: "30 days", tracking: "Rate your sleep (1=poor, 10=slept extremely well)" },
        { title: "Unplug and Unwind", chip: "1–4 WEEKS", desc: "Smart phones are used on average 5 times every hour. Release from the phone for a bit. Reconnect to the simpler things.", length: "1, 2, 3, or 4 weeks", tracking: "Time spent away from electronics" },
        { title: "Breathe In, Breathe Out", chip: "3 WEEKS", desc: "Deep breathing is a fantastic tool for the healthy toolbox. Take time out of hectic days to simply breathe.", length: "3 weeks", tracking: "Number of minutes" },
        { title: "Clean Up the Clutter", chip: "28 DAYS", desc: "Clutter overwhelms the brain and triggers stress that may lead to comfort eating. It's time to handle the clutter.", length: "28 days", tracking: "Time spent cleaning" },
        { title: "Reading Challenge", chip: "30 DAYS", desc: "Reading lowers stress, wards off Alzheimer's, and boosts brain health by up to 32%.", length: "30 days", tracking: "Reading time" },
        { title: "Choose Kindness", chip: "28 DAYS", desc: "Simple acts of kindness can start a chain reaction toward a happier environment for all.", length: "28 days", tracking: "Acts of kindness" },
        { title: "Breaking Bad Habits", chip: "28 DAYS", desc: "An engaging program designed to help you identify, understand, and ultimately break detrimental habits.", length: "28 days", tracking: "Complete weekly coaching" },
        { title: "Aim Smart: Goal-Setting", chip: "28 DAYS", desc: "Learn how to set a realistic goal that fits your life — and a practical process to help you follow through.", length: "28 days", tracking: "Complete weekly coaching" },
        { title: "Heart-Healthy Behaviors", chip: "28 DAYS", desc: "A four-week challenge built around movement, nutrition, stress management, and habit building.", length: "28 days", tracking: "Completion of weekly activity" },
        { title: "Watch Your Wallet", chip: "28 DAYS", desc: "Build realistic, sustainable financial habits that reduce unnecessary spending while maintaining quality of life.", length: "28 days", tracking: "Completion of weekly activity" },
        { title: "Journal: Daily Reflection", chip: "30 DAYS", desc: "Brief, daily reflection supports mental and emotional wellbeing — reducing stress, improving focus, and growing self-awareness.", length: "30 days", tracking: "Daily journal entry" },
      ],
    },
  ],
};
